const product = [
    {
        id:1,
        name: 'God of War',
        price: "200 EGP",
        img: "images/apple.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "mobile",
        desc : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id:2,
        name: 'Dead Stranding',
        price: "100 EGP",
        img: "images/microsoft.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",

    },
    {
        id : 3,
        name: 'The ast Of Us 2',
        price: "400 EGP",
        img: "images/hp.jpg",
        quantity:0,
        add: " add to cart",
        brand: "lap",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id : 4,
        name: 'God f War',
        price: "350 EGP",
        img: "images/apple.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "lap",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id : 5,
        name: 'Death Stranding',
        price: "150 EGP",
        img: "images/microsoft.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "lap",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id :6,
        name: 'The Last Of U 2',
        price: "333 EGP",
        img: "images/hp.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "pc",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    }
    ,
    {
        id :7,
        name: 'God of ar',
        price: "444 EGP",
        img: "images/apple.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "pc",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id : 8,
        name: 'Deah Stranding',
        price: "800 EGP",
        img: "images/microsoft.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id:9,
        name: 'Te Last Of Us 2',
        price: "350 EGP",
        img: "images/hp.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "pc",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    }
];
