const product = [
    {
        id: 1,
        name: 'Pull&Bear pantalon',
        price: 200,
        img: "image/pullpants.jpg",
        quantity: 0,
        add: " add to cart",
        brand: "clothes",
        desc : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 2,
        name: 'Samsung S22',
        price: 100,
        img: "image/samsung.png",
        quantity: 0,
        add: "add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",

    },
    {
        id: 3,
        name: 'Addidas short',
        price: 400,
        img: "image/addidas-short.jpeg",
        quantity:0,
        add: "add to cart",
        brand: "clothes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 4,
        name: 'Bersheka T-shirt',
        price: 350,
        img: "image/bersheka.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "clothes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 5,
        name: 'H&M t-shirt',
        price: 150,
        img: "image/nasa.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "clothes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 6,
        name: 'Ice watch',
        price: 333,
        img: "image/ice.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "watch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    }
    ,
    {
        id: 7,
        name: 'Rolex watch',
        price: 444,
        img: "image/rolex.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "watch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 8,
        name: 'Iphone 11 Pro Max',
        price: 800,
        img: "image/iphone11.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 9,
        name: 'Iphone X',
        price: 350,
        img: "image/iphonex.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 10,
        name: 'Iphone 8',
        price: 205,
        img: "image/Iphone8.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 11,
        name: 'xiaomi',
        price: 900,
        img: "image/xiaomi.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
    {
        id: 12,
        name: 'Montblanc watch',
        price: 550,
        img: "image/montblanc.jpg",
        quantity: 0,
        add: "add to cart",
        brand: "watch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates neque amet quos sit obcaecati dolorem molestiae consectetur fuga, voluptas perferendis blanditiis iusto officia beatae iure vel veniam voluptatem assumenda veritatis, eum rerum saepe tempore pariatur ea! Suscipit nisi impedit expedita, soluta asperiores sapiente aperiam officia veniam iste doloribus sunt vitae.",
    },
];
